spring:
  application:
    name: shop
  datasource:
    url: jdbc:mysql://localhost:3308/spring_base?characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Hongkong
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:/db/migration
    out-of-order: true
  logging:
    level:
      org.springframework.security:
        - debug
        - info
      org.springframework.web: error
      org.hibernate.SQL: debug
      org.hibernate.engine.QueryParameters: debug
      org.hibernate.engine.query.HQLQueryPlan: debug
      org.hibernate.type.descriptor.sql.BasicBinder: trace


server:
  port: 9090